userName: connectedhealth_0ZAka9
accessKey: 795Qi1UYRtf2G6eqDYYQ
framework: testng
app: bs://ce20e4010bb6e3cac2fe0c246923822a04f6455e
platforms:
  - platformName: iOS
    deviceName: iPhone 14 Pro Max
    platformVersion: 16.0
parallelsPerPlatform: 1
browserstackLocal: true
buildName: Test run for ios
projectName: MoAI_Mobile_Test_Automation