#userName: connectedhealth_0ZAka9
#accessKey: 795Qi1UYRtf2G6eqDYYQ
framework: testng
app: bs://95c0a6e0a808825636a0ca6a226d7b863a208e29
platforms:
  - platformName: iOS
    deviceName: iPhone 14 Pro Max
    platformVersion: 16.0
  - platformName: iOS
    deviceName: iPhone 12
    platformVersion: 15.5
  - platformName: iOS
    deviceName: iPhone XR
    platformVersion: 15
parallelsPerPlatform: 3
browserstackLocal: true
buildName: iOS_Test_Run
projectName: Heart-Monitor