userName: srinathr_6xBmwu
accessKey: 83qECYDqfsNawqciLDcE
framework: testng
app: bs://09c040a2183563b6053d888e5ba5e012c9e4a352
platforms:
  - platformName: android
    deviceName: Samsung Galaxy S22 Ultra
    platformVersion: 12.0
parallelsPerPlatform: 1
browserstackLocal: true
buildName: Test bed run for android
projectName: com.MoAI.healthCare