framework: testng
app: bs://2b32fee63fb6eb47847ffe8fd896840cea9a38f2
platforms:
  - platformName: android
    deviceName: Samsung Galaxy S22 Ultra
    platformVersion: 12.0
parallelsPerPlatform: 1
browserstackLocal: true
buildName: Test_run_ANDROID
projectName: Heart-Monitor