framework: testng
app: bs://2d592e474c36857ecad4d2cb70738c4e1fc4fa1b
platforms:
  - platformName: android
    deviceName: Samsung Galaxy S22 Ultra
    platformVersion: 12.0
parallelsPerPlatform: 1
browserstackLocal: true
buildName: ANDROID_Test_Run
projectName: Heart-Monitor